# Generated by Django 5.2.1 on 2025-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='brightness',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='document',
            name='contrast',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='document',
            name='grayscale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
