# Generated by Django 5.2.1 on 2025-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_document_brightness_document_contrast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='crop_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='crop_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='crop_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='crop_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='sepia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='vintage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
